### ISSUE TITLE
Content not in one line

### ISSUE THREAD

**Issue by rudnitskih** [RuchkoVlad/candies#3]
![image](https://user-images.githubusercontent.com/8848858/55665025-f0a4e380-5840-11e9-94f9-abe8eb1d0207.png)

**Comment by RuchkoVlad** [comment]
![width](https://user-images.githubusercontent.com/45762728/55682930-85433a80-5942-11e9-9f08-77e01b5ab491.png)

**Comment by RuchkoVlad** [comment]
![width](https://user-images.githubusercontent.com/45762728/55682984-2a5e1300-5943-11e9-9f4b-6f42757a7595.png)
